"""Prospective C6-B environment with 24 real, causal batch decision epochs.

The frozen Program O environment chooses one of four weekly count allocations.
This development-only environment instead pauses the exact transducer immediately
before each of the 24 action-independent batch arrivals.  The controller observes
the physical state generated by every earlier action and exogenous event, chooses
``P_H`` or ``P_C`` for the arriving 5,000-unit batch, and only then advances to the
next arrival.  Terminal metrics are independently recomputed by the frozen vector
transducer and must match the incremental state.

This is a new action-authority contract, not a reinterpretation of Program Q.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping, Sequence

import gymnasium as gym
from gymnasium import spaces
import numpy as np

from supply_chain.program_o_full_des import PRODUCTS
from supply_chain.program_o_full_des_transducer import (
    FullDESSkeleton,
    extract_full_des_skeleton,
    simulate_full_des_frontier,
)
from supply_chain.program_o_hobs import (
    posterior_after_week,
    predicted_request_share_c,
    transition_belief,
)
from supply_chain.program_o_ret_env import CONFIRMED_RET_CELLS, ProgramORetCell


BATCH_QUANTITY = 5_000.0
OBSERVATION_DIM = 21
PATTERN_SCHEDULER = {
    str(pattern): tuple(
        "P_C" if (pattern >> position) & 1 else "P_H" for position in range(3)
    )
    for pattern in range(8)
}


def bits_to_weekly_patterns(bits: Sequence[int]) -> tuple[int, ...]:
    values = tuple(int(value) for value in bits)
    if len(values) != 24 or any(value not in (0, 1) for value in values):
        raise ValueError("bits must contain exactly 24 binary actions")
    return tuple(
        values[3 * week]
        | (values[3 * week + 1] << 1)
        | (values[3 * week + 2] << 2)
        for week in range(8)
    )


@dataclass(frozen=True)
class PerBatchStructuredConfig:
    policy_id: str
    hysteresis: float = 0.0

    @property
    def config_id(self) -> str:
        return f"{self.policy_id}__{self.hysteresis:g}"


def structured_configurations() -> tuple[PerBatchStructuredConfig, ...]:
    """Small, finite family with the same binary action and observation."""
    return (
        PerBatchStructuredConfig("belief_pressure", 0.0),
        PerBatchStructuredConfig("belief_pressure", 2_500.0),
        PerBatchStructuredConfig("belief_pressure", 5_000.0),
        PerBatchStructuredConfig("backlog_first", 0.0),
        PerBatchStructuredConfig("inventory_balance", 0.0),
    )


def structured_action(
    raw: Mapping[str, Any], config: PerBatchStructuredConfig
) -> int:
    """Choose P_H=0 or P_C=1 from only the deployable observation payload."""
    on_hand = np.asarray(raw["on_hand"], dtype=float)
    backlog = np.asarray(raw["backlog_quantity"], dtype=float)
    in_flight = np.asarray(raw["in_flight_quantity"], dtype=float)
    position = on_hand + in_flight - backlog
    previous = raw["previous_action"]
    policy = config.policy_id
    if policy == "backlog_first":
        pressure = backlog[0] - backlog[1]
    elif policy == "inventory_balance":
        pressure = position[1] - position[0]
    elif policy == "belief_pressure":
        share_c = float(raw["predicted_share_c"])
        horizon_demand = 15_000.0 * np.asarray((share_c, 1.0 - share_c))
        pressure = (horizon_demand[0] - position[0]) - (
            horizon_demand[1] - position[1]
        )
    else:
        raise ValueError(f"unknown structured policy: {policy}")
    if previous is not None and abs(float(pressure)) <= float(config.hysteresis):
        return int(previous)
    return int(float(pressure) > 0.0)


class ProgramOPerBatchEnv(gym.Env[np.ndarray, int]):
    """Exact 24-epoch C6-B environment over one Program O skeleton."""

    metadata = {"render_modes": []}

    def __init__(
        self,
        *,
        scheduler: Mapping[str, Sequence[str]],
        tape_seed_start: int,
        tape_seed_end: int,
        cells: Sequence[ProgramORetCell] = CONFIRMED_RET_CELLS,
        belief_model_persistence: float = 0.75,
        belief_model_dominant_share: float = 0.90,
    ) -> None:
        super().__init__()
        if int(tape_seed_end) < int(tape_seed_start):
            raise ValueError("tape_seed_end must be >= tape_seed_start")
        if not cells:
            raise ValueError("at least one cell is required")
        self.scheduler = {str(key): tuple(value) for key, value in scheduler.items()}
        self.tape_seed_start = int(tape_seed_start)
        self.tape_seed_end = int(tape_seed_end)
        self.cells = tuple(cells)
        self.belief_model_persistence = float(belief_model_persistence)
        self.belief_model_dominant_share = float(belief_model_dominant_share)
        self.action_space = spaces.Discrete(2)
        self.observation_space = spaces.Box(
            low=0.0, high=1.0, shape=(OBSERVATION_DIM,), dtype=np.float32
        )
        self._episode_index = 0
        self._skeleton: FullDESSkeleton | None = None
        self._cell: ProgramORetCell | None = None
        self._events: list[tuple[float, int, str, Any]] = []
        self._event_index = 0
        self._current_batch: tuple[float, int, int] | None = None
        self._actions: list[int] = []
        self._now = 0.0

    def _tape_seed(self) -> int:
        count = self.tape_seed_end - self.tape_seed_start + 1
        if self._episode_index >= count:
            raise RuntimeError("C6-B training tape namespace exhausted")
        return self.tape_seed_start + self._episode_index

    def _build_skeleton(self, seed: int, cell: ProgramORetCell) -> FullDESSkeleton:
        skeleton, _ = extract_full_des_skeleton(
            seed=int(seed),
            scheduler=self.scheduler,
            regime_persistence=float(cell.regime_persistence),
            dominant_share=float(cell.dominant_share),
            downstream_freight_physics_mode="fixed_clock_physical_v1",
        )
        return skeleton

    def _initialize_state(self) -> None:
        if self._skeleton is None:
            raise RuntimeError("skeleton missing")
        skeleton = self._skeleton
        n_orders = len(skeleton.order_times)
        self._inventory = np.asarray(skeleton.opening_inventory, dtype=float).copy()
        self._pending = np.zeros(n_orders, dtype=bool)
        self._created = np.zeros(n_orders, dtype=bool)
        self._released = np.zeros(n_orders, dtype=bool)
        self._oat = np.full(n_orders, np.inf, dtype=float)
        self._bt = np.zeros(n_orders, dtype=np.uint8)
        self._requested_product = np.asarray(
            [PRODUCTS.index(value) for value in skeleton.order_products], dtype=np.int8
        )
        self._quantities = np.asarray(skeleton.order_quantities, dtype=float)
        self._opt = np.asarray(skeleton.order_times, dtype=float)
        contingent = (
            np.zeros(n_orders, dtype=bool)
            if skeleton.order_contingent is None
            else np.asarray(skeleton.order_contingent, dtype=bool)
        )
        self._priority_order = np.lexsort(
            (np.arange(n_orders), self._opt, self._quantities, 1 - contingent.astype(np.uint8))
        )
        completion = (
            tuple(float(value) + 48.0 for value in skeleton.release_slots)
            if skeleton.release_completion_slots is None
            else tuple(map(float, skeleton.release_completion_slots))
        )
        available = (
            tuple(True for _ in skeleton.release_slots)
            if skeleton.release_available is None
            else tuple(map(bool, skeleton.release_available))
        )
        self._release_completion = completion
        self._release_available = available
        events: list[tuple[float, int, str, Any]] = []
        for index, time in enumerate(skeleton.release_slots):
            events.append((float(time), 0, "release", int(index)))
        for time, week, position in skeleton.batch_arrivals:
            events.append((float(time), 1, "batch", (int(week), int(position))))
        for index, time in enumerate(skeleton.order_times):
            events.append((float(time), 2, "demand", int(index)))
        self._events = sorted(events)
        self._event_index = 0
        self._current_batch = None
        self._actions = []
        self._now = float(skeleton.decision_start)

    def _process_release(self, release_index: int) -> None:
        if not self._release_available[release_index]:
            return
        chosen = -1
        for order_index in self._priority_order:
            if not self._created[order_index] or not self._pending[order_index]:
                continue
            product = self._requested_product[order_index]
            if self._inventory[product] + 1e-9 >= self._quantities[order_index]:
                chosen = int(order_index)
                break
        if chosen < 0:
            return
        product = int(self._requested_product[chosen])
        self._inventory[product] -= float(self._quantities[chosen])
        self._pending[chosen] = False
        self._released[chosen] = True
        self._oat[chosen] = float(self._release_completion[release_index])

    def _process_demand(self, order_index: int) -> None:
        prior = np.arange(order_index)
        if len(prior):
            late = (self._opt[prior] + 48.0 <= self._now + 1e-12) & (
                self._oat[prior] > self._now + 1e-12
            )
            self._bt[order_index] = np.uint8(min(60, int(late.sum())))
        self._pending[order_index] = True
        self._created[order_index] = True

    def _advance_to_next_batch(self) -> bool:
        self._current_batch = None
        while self._event_index < len(self._events):
            now, _priority, kind, payload = self._events[self._event_index]
            self._event_index += 1
            self._now = float(now)
            if kind == "batch":
                week, position = payload
                self._current_batch = (float(now), int(week), int(position))
                return True
            if kind == "release":
                self._process_release(int(payload))
            elif kind == "demand":
                self._process_demand(int(payload))
        return False

    def _finish_events(self) -> None:
        while self._event_index < len(self._events):
            now, _priority, kind, payload = self._events[self._event_index]
            self._event_index += 1
            self._now = float(now)
            if kind == "batch":
                raise AssertionError("unprocessed batch remained after the 24th action")
            if kind == "release":
                self._process_release(int(payload))
            elif kind == "demand":
                self._process_demand(int(payload))

    def _belief(self) -> tuple[float, float]:
        if self._skeleton is None:
            raise RuntimeError("skeleton missing")
        start = float(self._skeleton.decision_start)
        current_week = min(7, max(0, int((self._now - start) // 168.0)))
        belief = 0.5
        for week in range(current_week + 1):
            lo = start + 168.0 * week
            hi = lo + 168.0
            labels = [
                self._skeleton.order_products[index]
                for index, time in enumerate(self._skeleton.order_times)
                if self._created[index] and lo <= float(time) < min(hi, self._now - 1e-12)
            ]
            if labels:
                belief = posterior_after_week(
                    belief,
                    labels,
                    dominant_share=self.belief_model_dominant_share,
                )
            if week < current_week:
                belief = transition_belief(
                    belief,
                    regime_persistence=self.belief_model_persistence,
                )
        return belief, predicted_request_share_c(
            belief, dominant_share=self.belief_model_dominant_share
        )

    def raw_observation(self) -> dict[str, Any]:
        if self._skeleton is None or self._current_batch is None:
            raise RuntimeError("reset() must be called before requesting an observation")
        _time, week, position = self._current_batch
        backlog = np.zeros(2, dtype=float)
        backlog_orders = np.zeros(2, dtype=int)
        max_age = np.zeros(2, dtype=float)
        in_flight = np.zeros(2, dtype=float)
        for index in range(len(self._opt)):
            product = int(self._requested_product[index])
            if self._pending[index]:
                backlog[product] += self._quantities[index]
                backlog_orders[product] += 1
                max_age[product] = max(max_age[product], self._now - self._opt[index])
            elif self._released[index] and self._oat[index] >= self._now - 1e-12:
                in_flight[product] += self._quantities[index]
        belief, predicted = self._belief()
        return {
            "batch_index": len(self._actions),
            "week": int(week),
            "position": int(position),
            "decision_time": float(self._now),
            "on_hand": self._inventory.copy(),
            "backlog_quantity": backlog,
            "backlog_orders": backlog_orders,
            "max_backlog_age": max_age,
            "in_flight_quantity": in_flight,
            "belief_c": float(belief),
            "predicted_share_c": float(predicted),
            "previous_action": None if not self._actions else int(self._actions[-1]),
            "remaining_decisions": 24 - len(self._actions),
        }

    def _normalized_observation(self) -> np.ndarray:
        raw = self.raw_observation()
        values: list[float] = []
        for key in ("on_hand", "backlog_quantity"):
            values.extend(float(value) / 120_000.0 for value in raw[key])
        values.extend(float(value) / 48.0 for value in raw["backlog_orders"])
        values.extend(float(value) / 1_344.0 for value in raw["max_backlog_age"])
        values.extend(float(value) / 120_000.0 for value in raw["in_flight_quantity"])
        values.extend((raw["belief_c"], raw["predicted_share_c"]))
        values.extend(
            (
                raw["batch_index"] / 23.0,
                raw["week"] / 7.0,
                raw["position"] / 2.0,
                raw["remaining_decisions"] / 24.0,
            )
        )
        previous = np.zeros(3, dtype=float)
        previous[0 if raw["previous_action"] is None else 1 + raw["previous_action"]] = 1.0
        values.extend(previous.tolist())
        # Two strictly historical demand-count channels for the current week.
        start = float(self._skeleton.decision_start) + 168.0 * raw["week"]
        counts = [0, 0]
        for index, time in enumerate(self._skeleton.order_times):
            if self._created[index] and start <= float(time) < self._now - 1e-12:
                counts[int(self._requested_product[index])] += 1
        values.extend(value / 6.0 for value in counts)
        vector = np.asarray(values, dtype=np.float32)
        if vector.shape != (OBSERVATION_DIM,):
            raise AssertionError(f"C6-B observation shape drift: {vector.shape}")
        return np.clip(vector, 0.0, 1.0)

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        super().reset(seed=seed)
        options = options or {}
        cell_index = int(options.get("cell_index", self._episode_index % len(self.cells)))
        if cell_index not in range(len(self.cells)):
            raise ValueError("cell_index outside C6-B cell set")
        self._cell = self.cells[cell_index]
        tape_seed = int(options.get("tape_seed", self._tape_seed()))
        supplied = options.get("skeleton")
        self._skeleton = (
            supplied
            if isinstance(supplied, FullDESSkeleton)
            else self._build_skeleton(tape_seed, self._cell)
        )
        self._episode_index += 1
        self._initialize_state()
        if not self._advance_to_next_batch():
            raise AssertionError("skeleton contains no batch arrivals")
        return self._normalized_observation(), {
            "tape_seed": tape_seed,
            "cell_id": self._cell.cell_id,
            "raw_observation": self.raw_observation(),
        }

    def step(
        self, action: int
    ) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        if self._skeleton is None or self._current_batch is None:
            raise RuntimeError("reset() must be called before step()")
        value = int(action)
        if value not in (0, 1):
            raise ValueError("C6-B action must be 0=P_H or 1=P_C")
        product_index = 0 if value == 1 else 1
        self._inventory[product_index] += BATCH_QUANTITY
        self._actions.append(value)
        if len(self._actions) < 24:
            if not self._advance_to_next_batch():
                raise AssertionError("fewer than 24 batch epochs")
            return self._normalized_observation(), 0.0, False, False, {
                "raw_observation": self.raw_observation()
            }

        self._current_batch = None
        self._finish_events()
        patterns = bits_to_weekly_patterns(self._actions)
        direct_trace: dict[str, Any] = {}
        metrics = simulate_full_des_frontier(
            skeleton=self._skeleton,
            scheduler=PATTERN_SCHEDULER,
            calendars=np.asarray([patterns], dtype=np.uint8),
            trace_out=direct_trace,
        )
        terminal = {key: float(value[0]) for key, value in metrics.items()}
        completed = self._oat <= float(self._skeleton.score_time) + 1e-12
        direct_completed = len(self._oat) - int(round(terminal["unresolved_orders"]))
        if int(completed.sum()) != direct_completed:
            raise AssertionError("incremental/vector completed-order parity failure")
        direct_oat = np.asarray(
            [np.inf if row["OATj"] is None else float(row["OATj"]) for row in direct_trace["orders"]]
        )
        direct_bt = np.asarray(
            [int(row["ret_bt_at_request"]) for row in direct_trace["orders"]], dtype=np.uint8
        )
        if not np.array_equal(self._oat, direct_oat):
            raise AssertionError("incremental/vector OAT parity failure")
        if not np.array_equal(self._bt, direct_bt):
            raise AssertionError("incremental/vector backlog-counter parity failure")
        if not np.allclose(
            self._inventory,
            [terminal["ending_inventory_P_C"], terminal["ending_inventory_P_H"]],
            atol=1e-12,
            rtol=0.0,
        ):
            raise AssertionError("incremental/vector ending-inventory parity failure")
        observation = np.zeros(self.observation_space.shape, dtype=np.float32)
        return observation, float(terminal["ret_visible"]), True, False, {
            "actions": list(self._actions),
            "weekly_patterns": list(patterns),
            "metrics": terminal,
        }
