#!/usr/bin/env python3
"""Adjudicate the tested-candidate residual after Q-R1 D1.

The per-episode selector is intentionally privileged and therefore only an
upper bound over calendars already generated by D1.  It cannot authorize a
learner by itself.  A material bound routes to structured-family calibration;
an immaterial bound closes only this tested calendar family.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from datetime import datetime, timezone
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]


def clustered_lcb(values: dict[int, list[float]], seed: int = 20260721) -> float:
    roots = sorted(values)
    means = np.asarray([np.mean(values[root]) for root in roots], dtype=float)
    rng = np.random.default_rng(seed)
    draws = rng.integers(0, len(means), size=(5000, len(means)))
    return float(np.quantile(means[draws].mean(axis=1), 0.025))


def run(source: Path) -> dict:
    payload = json.loads(source.read_text())
    rows = payload["rows"]
    grouped: dict[tuple[str, int, int], list[dict]] = defaultdict(list)
    for row in rows:
        grouped[(row["persistence_mode"], row["history_root"], row["campaign_index"])].append(row)
    by_mode = {}
    all_deltas: dict[int, list[float]] = defaultdict(list)
    persistent_deltas: dict[int, list[float]] = defaultdict(list)
    selected_rows = []
    for mode in ("iid", "persistent_0p75", "persistent_0p90"):
        mode_delta: dict[int, list[float]] = defaultdict(list)
        divergence = []
        theta_delta: dict[str, list[float]] = defaultdict(list)
        for (row_mode, root, campaign), candidates in grouped.items():
            if row_mode != mode or campaign == 0:
                continue
            retained = next(row for row in candidates if row["arm"] == "retained_exact_bayes_mpc")
            best = max(candidates, key=lambda row: (row["early_ret_2w"], row["arm"]))
            delta = float(best["early_ret_2w"] - retained["early_ret_2w"])
            mode_delta[root].append(delta)
            all_deltas[root].append(delta)
            if mode != "iid":
                persistent_deltas[root].append(delta)
            divergence.append(best["calendar"][:2] != retained["calendar"][:2])
            theta_delta[retained["theta_id"]].append(delta)
            selected_rows.append({
                "persistence_mode": mode,
                "history_root": root,
                "campaign_index": campaign,
                "theta_id": retained["theta_id"],
                "selected_arm": best["arm"],
                "retained_prefix": retained["calendar"][:2],
                "selected_prefix": best["calendar"][:2],
                "delta_early_ret_2w": delta,
            })
        values = [value for root in mode_delta for value in mode_delta[root]]
        by_mode[mode] = {
            "tested_oracle_minus_retained_mean": float(np.mean(values)),
            "history_clustered_lcb95": clustered_lcb(mode_delta),
            "action_divergence": float(np.mean(divergence)),
            "theta_mean_deltas": {key: float(np.mean(value)) for key, value in theta_delta.items()},
            "n_pairs": len(values),
        }
    values = [value for root in all_deltas for value in all_deltas[root]]
    persistent_values = [value for root in persistent_deltas for value in persistent_deltas[root]]
    pooled_all_modes_descriptive = {
        "tested_oracle_minus_retained_mean": float(np.mean(values)),
        "history_clustered_lcb95": clustered_lcb(all_deltas),
        "action_divergence": float(np.mean([
            row["retained_prefix"] != row["selected_prefix"] for row in selected_rows
        ])),
        "n_pairs": len(values),
    }
    primary_rows = [row for row in selected_rows if row["persistence_mode"] != "iid"]
    primary_persistent = {
        "tested_oracle_minus_retained_mean": float(np.mean(persistent_values)),
        "history_clustered_lcb95": clustered_lcb(persistent_deltas),
        "action_divergence": float(np.mean([
            row["retained_prefix"] != row["selected_prefix"] for row in primary_rows
        ])),
        "n_pairs": len(persistent_values),
    }
    material = (
        primary_persistent["tested_oracle_minus_retained_mean"] >= 0.02
        and primary_persistent["history_clustered_lcb95"] > 0.0
        and primary_persistent["action_divergence"] >= 0.10
        and all(by_mode[mode]["tested_oracle_minus_retained_mean"] >= -0.005 for mode in ("persistent_0p75", "persistent_0p90"))
    )
    prospective_all_modes_pass = (
        pooled_all_modes_descriptive["tested_oracle_minus_retained_mean"] >= 0.02
        and pooled_all_modes_descriptive["history_clustered_lcb95"] > 0.0
        and pooled_all_modes_descriptive["action_divergence"] >= 0.10
    )
    if prospective_all_modes_pass:
        verdict = "PASS_D3_TESTED_RESIDUAL_BOUND_REQUIRES_STRUCTURED_CALIBRATION"
    elif material:
        verdict = "STOP_D3_PROSPECTIVE_GATE_POSTHOC_PERSISTENT_SIGNAL_REQUIRES_REPLICATION"
    else:
        verdict = "STOP_D3_TESTED_HISTORY_ORACLE_RESIDUAL_BELOW_GATE"
    return {
        "schema_version": "q_r1_d3_tested_residual_bound_v1",
        "claim_status": "EXPLORATORY_NO_CLAIM",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "source": str(source),
        "bound_definition": "per-episode best early_ret_2w among D1-generated arm calendars minus retained exact-Bayes MPC",
        "critical_boundary": "privileged selector over a tested calendar family; not a full-DES/POMDP upper bound",
        "prospective_gate_interpretation": "all three modes pooled, as first implemented before inspecting D3",
        "posthoc_estimand_correction": "persistent_0p75 and persistent_0p90 only; scientifically motivated because iid is a null, but it cannot upgrade this burned run without replication",
        "primary_persistent": primary_persistent,
        "pooled_all_modes_descriptive": pooled_all_modes_descriptive,
        "by_persistence": by_mode,
        "selected_rows": selected_rows,
        "verdict": verdict,
        "structured_family_calibration_required": prospective_all_modes_pass,
        "fresh_burned_replication_authorized": bool(material and not prospective_all_modes_pass),
        "learner_authorized": False,
        "missing_before_learner_authorization": [
            "fresh burned replication of persistent-only D3 estimand",
            "universal retained structured family selected in calibration",
            "delayed-history placebo",
            "observable conversion of the privileged residual",
        ] if material else [],
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=ROOT / "results/q_r1/d1_demand_memory_v1/result.json")
    parser.add_argument("--output", type=Path, default=ROOT / "results/q_r1/d3_residual_bound_v1/result.json")
    args = parser.parse_args()
    payload = run(args.source)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    print(json.dumps({key: value for key, value in payload.items() if key != "selected_rows"}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
